const CACHE_LIFETIME = 7200000 // 2 ore -> 1000 * 60 * 60 * 2
const LOCATION_CACHE_KEY = "@USER_LOCATION_CACHE_KEY"
const CITY_CACHE_KEY = "@USER_LOCATION_CITY_CACHE_KEY"

export {
  CACHE_LIFETIME,
  LOCATION_CACHE_KEY,
  CITY_CACHE_KEY
}